### ISSUE TITLE
Improve link format

### ISSUE THREAD

**Issue by madwort** [madwort/link_scraper#2]
```
<dl style="padding-left: 30px;">
  <dt><b>John Zorn</b></dt>
  <dd style="padding-left: 10px;"><a href="https://en.wikipedia.org/wiki/John_Zorn" target="_blank">-https://en.wikipedia.org/wiki/John_Zorn</a></dd>
</dl>
```

(markup gobbles up html so go into edit view to see)

This seems to work and look the best from what I've played with (note the "-" before the display name in the href)

Edit: you can use three backticks around raw html to display in github comments.

**Comment by rconstanzo** [comment]
fixed it (i think) (handy to know about raw html)

**Comment by madwort** [comment]
Nice! Missed some quotes that needed escaping, but otherwise great.
