### ISSUE TITLE
link scraper not finding embedded videos

### ISSUE THREAD

**Issue by rconstanzo** [madwort/link_scraper#3]
because of iframe?

**Comment by rconstanzo** [comment]
All text for thesis is done, and it looks like it's searching the whole body too. If it's finding embedded videos could you run/dump it again so I can start cleaning it and putting it in place?

**Comment by madwort** [comment]
not finding iframes yet, but can do.

**Comment by madwort** [comment]
So, to clarify, do you want to pick up embedded videos into this list? Ones that look like this (from the  decisions page):

```
<iframe width="640" height="360" src="https://www.youtube.com/embed/wdUwYcjpc2c?rel=0" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
```

**Comment by madwort** [comment]
(If so - what should I put as source text - just the url?)
