### ISSUE TITLE
parser wishlist

### ISSUE THREAD

**Issue by rconstanzo** [madwort/link_scraper#5]
```
-removing duplicate urls (ie www.rodrigoconstanzo.com/ and www.rodrigoconstanzo.com/)
-removing wp-specific urls (#respond like : <a href="/grassi-box/#respond"> and <a href="http://www.rodrigoconstanzo.com/2013/05/flute-snare/" target="_blank">next post&raquo;</a>)
-scrape youtube embeds
```

**Comment by madwort** [comment]
> removing wp-specific urls (#respond like : `<a href="/grassi-box/#respond"> and <a href="http://www.rodrigoconstanzo.com/2013/05/flute-snare/" target="_blank">next post&raquo;</a>`)

should I remove all internal links (ie. with prefix `href="/` or `href="http://www.rodrigoconstanzo.com` ) or do you need to keep them? In which case I guess we need a blacklist of url parts (eg. `#respond`) and link text parts (eg. `next post`)?
